# Generated by Django 5.1 on 2024-08-25 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_tdindex'),
        ('user', '0002_keyword_notification_scrap_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='keyword',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='notice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notice.notice'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AlarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('alarm_date', models.DateTimeField()),
                ('alarm_days', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
