# Generated by Django 5.1 on 2024-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_tdindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notitype',
            field=models.CharField(default='GENERALNOTICE', max_length=30),
            preserve_default=False,
        ),
    ]
