# Generated by Django 5.1 on 2024-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_notitype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachments',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='base_url',
            field=models.URLField(default="https://www.dongguk.edu"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='imgs',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='links',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='org_code',
            field=models.CharField(default='MAIN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='sub_code',
            field=models.CharField(default='MAIN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='univ_code',
            field=models.CharField(default='DONGGUK', max_length=50),
            preserve_default=False,
        ),
    ]
