# Generated by Django 5.1 on 2024-09-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_notice_attachments_notice_base_url_notice_imgs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='ocr_data',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
